centreon/centreon-ui

- src/ExtensionDeletePopup/index.js
- src/ExtensionDetailsPopup/index.js
- src/ExtensionsHolder/index.js
- src/FileUpload/index.js
- src/TopFilters/index.js
Improving the display of errors and getting around bind call using experimental plublic class fields syntax
>  enh(ui): better display of errors on file upload

- src/ExtensionDetailsPopup/index.js
- src/ExtensionsHolder/index.js
+ remove license button from extension detailed popin
>  enh(ui): improve license display in card footer

- Jenkinsfile
to build a storybook container
> chore(build): add bundle stage in jenkinsfile

- src/ExtensionsHolder/index.js
As I'm aware - I push modified fils into centreon-react-components and then centreon could be updated after merge.. 
I tested the modifications on my VM - that works perfectlly.
> MON-3782 #comment modification of wording

- package.json
#Ref https://centreon.atlassian.net/browse/MON-3947
This adds a script to run babel with the --watch and --source-maps options (for development).
> enh(core): Add npm script to transpile with dev options.

- src/Table/TableCustom/index.js
apply change by Nikola that was missing in previous branch merge, nonbreaking change
> update(table): custom table change style

- src/InputField/SearchInput/index.jsx
- src/Wizard/ActionBar.jsx
- src/Wizard/ActionBar.test.jsx
- src/Wizard/index.jsx
- stories/Wizard.jsx
* forward Formik's bag property in wizard pages
* disable actionbar's next button if form is not valid
* use theme in SearchInput component
> enh(wizard): forward formik bag in props

- src/Table/TableCustom/index.js
- src/Table/TableCustom/index.test.jsx
This is required for https://centreon.atlassian.net/browse/BAM-928 (19.10.x)
> fix(ui): Don't display null in case of empty multiColumn value

- src/Table/TableCustom/index.js
```
if (!value) {
...
}
```
returns `true` if it's 0 :(
> fix(ui): Fix not displaying threshold with 0 values

- src/index.ts
- src/utils/copy.ts
Since Centreon and Centreon Auto-Discovery copies text to clipboard, we decided to move this function to centreon/ui
> Add copy function

- src/Listing/index.test.jsx
- src/Listing/index.tsx
> Fix(Listing): Reset page to 0 when when changing page limit

- src/Panel/Section/index.tsx
> fix(Section Panel): Remove scrollbar at bottom of Section Panel

- package-lock.json
> chore(npm): Re-generate package-lock

- src/InputField/Select/Autocomplete/Draggable/index.tsx
This fixes a high z index to avoid that the dragged element disappear under MUI Dialog
> fix(Autocomplete/Draggable): Fix z index

- .github/CODEOWNERS
add codeowners to assign automatically reviewers
> enh(ci): add codeowners

- src/InputField/Select/Autocomplete/Connected/index.tsx
- src/InputField/Select/Autocomplete/Multi/index.tsx
- src/InputField/Select/Autocomplete/index.tsx
- src/InputField/Select/Option.tsx
- src/InputField/Select/index.tsx
This reduces slightly the font size of select options.
> enh(Select): Reduce the size of Select option texts

- src/Panel/index.tsx
This is needed in the Resource status because I need the bounds (top & bottom) of the panel container
> enh(ListingPage/Panel): Forward Panel ref 

- src/Listing/Cell/DataCell.tsx
- src/Listing/Cell/index.tsx
- src/Listing/Header.tsx
- src/Listing/models.ts
- tsconfig.json
This adds a compact mode for small Listing and fix the row color condition.
> enh(Listing): Add compact mode and fix color condition

- src/InputField/Select/Autocomplete/Connected/index.tsx
- src/api/buildListingEndpoint/getSearchQueryParameterValue.ts
- src/api/buildListingEndpoint/index.test.ts
- src/api/buildListingEndpoint/models.ts
Add a default search parameter to the Autocomplete and add a simple "value" to the search conditions within the buildListingEndoint function.
> enh(Autocomplete): Add fix parameters to autocomplete endpoint

- src/Listing/index.tsx
same as https://github.com/centreon/centreon-ui/pull/333 for 20.10.x branch
> enh(Listing): add getId prop

- src/Panel/Tab.tsx
- src/Panel/index.tsx
- src/index.ts
> feat(Panel): Add Tab component and set minHeight to 40

- src/InputField/Select/Autocomplete/Connected/index.tsx
- src/InputField/Select/Autocomplete/index.tsx
- src/InputField/Select/Option.tsx
> fix(Autocomplete): Fix equality checking and prevent multi-select close when options are selected
